stolostron/cluster-curator-controller

- cmd/curator/curator.go
- pkg/controller/launcher/job.go
- pkg/jobs/ansible/job.go
- pkg/jobs/create/hive.go
- pkg/jobs/secrets/secrets.go
- pkg/jobs/utils/helpers.go
Signed off by: Joshua Packer
* Fix a number of line length warning from Sonarcloud
* Remove a 4+ loop/if depth section in AnsibleJob monitoring
* Start to track the AnsibleJob namespacedName in the ConfigMap for the Console to use.
/cc @leena-jawale @hanqiuzh
> Fix the final sonarcloud warnings and adjust AnsibleJob status monitoring

- cmd/controller/controller.go
- cmd/curator/curator.go
- deploy/controller/clusterrole.yaml
- pkg/controller/launcher/job.go
- pkg/controller/launcher/job_test.go
- pkg/jobs/importer/managedcluster.go
- pkg/jobs/importer/managedcluster_test.go
- pkg/jobs/rbac/rbac.go
- pkg/jobs/rbac/rbac_test.go
- pkg/jobs/utils/helpers.go
- pkg/jobs/utils/helpers_test.go
Signed off by: @jnpacker 
* Add support to monitor ManagedClusterInfos - Instead of ManagedCluster, this saves a RoleBinding resource
* Added extend cluster-installer role (not used as Hive controller overwrites this role periodically)
* Added flag.set so that verbose level 2 is now available
* End to end deployment validated
* Add TTL for the curator-job pod
> ManagedClusterInfos monitoring

- deploy/controller/clusterrole.yaml
* Missing rules in cluster-curator clusterRole that keep the pods from coming online.
```
configmaps: create, get
pods:           get
```
https://github.com/open-cluster-management/backlog/issues/10674
```bash
E0319 13:27:15.074157       1 controller.go:128] configmaps is forbidden: User "system:serviceaccount:open-cluster-management:cluster-curator" cannot create resource "configmaps" in API group "" in the namespace "open-cluster-management": RBAC: clusterrole.rbac.authorization.k8s.io "open-cluster-management.cluster-lifecycle.cluster-curator" not foundDid not obtain leader cluster-curator-controller-lock
```
```bash
E0319 13:25:15.583227       1 controller.go:128] configmaps "cluster-curator-controller-lock" is forbidden: User …
```
> Fix leader election rules.

- controllers/scale_controller_test.go
* Include the scale-cluster-curator-controller_test.go for manual scale testing and pod profiling
> Add scale test in dormant (-short) mode

- pkg/jobs/hive/hive.go
- pkg/jobs/hive/hive_test.go
* Push the timeout up to 3min from 30s.
> Increase the timeout when looking for the hive provisioning job to 3min

- cmd/curator/curator.go
- controllers/clustercurator_controller.go
- deploy/controller/clusterrole.yaml
- deploy/crd/cluster.open-cluster-management.io_clustercurators.yaml
- pkg/api/v1beta1/clustercurator_types.go
- pkg/controller/launcher/job.go
- pkg/jobs/ansible/job.go
- pkg/jobs/hive/hive.go
- pkg/jobs/hive/hive_test.go
- pkg/jobs/importer/managedcluster.go
- pkg/jobs/rbac/rbac.go
- pkg/jobs/rbac/rbac_test.go
- pkg/jobs/utils/helpers.go
- pkg/jobs/utils/helpers_test.go
Signed off by: @jnpacker <jpacker@redhat.com>
* Add `desiredCuration: destroy`
* Includes tests
* Requires that the user delete the ManageCluster resource as this requires higher elevated priviledge.
> Destroy curation

- build/before-make.sh
- deploy/controller/clusterrole.yaml
- pkg/jobs/ansible/job.go
- pkg/jobs/ansible/job_test.go
- pkg/jobs/rbac/rbac.go
- pkg/jobs/rbac/rbac_test.go
- pkg/jobs/utils/helpers.go
* Swap Machinepool for install_config. 
* Choose which install_config keys to include so that we do NOT expose any secret data
* Still requires a change to allow `get` for secrets.
> Replace machinepool with install_config in extra_vars

- pkg/jobs/ansible/job.go
- pkg/jobs/ansible/job_test.go
- pkg/jobs/utils/helpers.go
* Opt-out of `platform` install-config data parameters (currently we opt-in by choosing specific keys)
* This is a much shorter code path, but risks introduction of sensitive data if a new provider has values are introduced at some point.
* The alternate is also true, if new keys are introduced, that are NOT sensitive, in the opt-in approach those would be missed till we made a change.
> Opt-out of sensitive keys (remove when found)

- Dockerfile.prow
The related issue: https://github.com/open-cluster-management/backlog/issues/15570
> remove reference to image with old go version

- go.mod
- go.sum
The related issue: https://github.com/stolostron/backlog/issues/19219
> enforce to use the latest ocm api

- go.mod
- go.sum
The related issue: https://github.com/stolostron/backlog/issues/22260
> fix cve-2022-29810 for 2.4 release

- go.mod
- go.sum
The related issue: https://github.com/stolostron/backlog/issues/22260
> fix cve-2022-29810 in 2.3 branch

- Dockerfile.prow
- go.mod
Related issue: https://github.com/stolostron/backlog/issues/26639
> rollback golang to 1.18

- cmd/manager/main.go
- deploy/controller/deployment.yaml
- sonar-project.properties
This PR adds the leader election settings with default values:
``` 
--leader-election-lease-duration=136s
--leader-election-renew-deadline=107s
--leader-election-retry-period=26s
```
Updates sonar properties to ignore the controllers `main.go`
> Add leader election settings

- README.md
- cmd/curator/curator.go
- cmd/curator/curator_test.go
- controllers/clustercurator_controller.go
- docs/README.md
- pkg/controller/launcher/job.go
- pkg/controller/launcher/job_test.go
- pkg/jobs/ansible/job.go
- pkg/jobs/hive/hive.go
- pkg/jobs/hive/hive_test.go
- pkg/jobs/hypershift/hypershift.go
- pkg/jobs/hypershift/hypershift_test.go
- pkg/jobs/rbac/rbac.go
- pkg/jobs/rbac/rbac_test.go
- pkg/jobs/utils/helpers.go
- pkg/jobs/utils/helpers_test.go
https://issues.redhat.com/browse/ACM-6494
- Add support for Hypershift clusters AWS, Agent, and KubeVirt
- Supported operations `install`, `upgrade`, `destroy`
- AWS doesn't support `destroy`
- `ClusterCurator` CR need to be created in the same namespace as `HostedCluster` this is different than standalone OCP where the `ClusterCurator` CR need to be in the namespace with the cluster name
- Other than that all usage is same as standalone OCP, `ClusterCurator` will auto-detect between Hosted and Standalone clusters
> ACM-6494 Initial ClusterCurator Hypershift support

- pkg/jobs/hive/hive.go
- pkg/jobs/hive/hive_test.go
https://issues.redhat.com/browse/ACM-9334
- Disable availableUpdates version checking if force upgrade annotation exists
> ACM-9334 Add annotation to allow upgrading to non-recommended OCP versions

- pkg/jobs/utils/helpers.go
https://issues.redhat.com/browse/ACM-9123
```
DesiredCuration: upgrade Version (4.12.45;;) Failed - hostedclusters.hypershift.openshift.io \"mytestcluster45\" is forbidden: User \"system:serviceaccount:mytestcluster45:cluster-installer\" cannot get resource \"hostedclusters\" in API group \"hypershift.openshift.io\" in the namespace \"mytestcluster45\""
```
- Fix HostedCluster permission issue for users going from 2.8 to 2.9
- Ignore HostedCluster CRD not found error if Hypershift operator is not installed
- Ignore `is forbidden` permissions error
> ACM-9123 Fix HostedCluster permission issue for users going from 2.8 to 2.9

- pkg/controller/launcher/job.go
Curator pods were lacking with custom/generic labels, this makes it hard to target the curator pods with network policies.
> Push Labels from curator CR to curator pods

- pkg/jobs/hive/hive.go
https://issues.redhat.com/browse/ACM-11417
- Backport clusterversion retry fix to ACM 2.8
> ACM-11417 Backport clusterversion retry fix to ACM 2.8

- cmd/curator/curator.go
- cmd/curator/curator_test.go
- controllers/scale_controller_test.go
- go.mod
- go.sum
- pkg/jobs/utils/helpers.go
The https://github.com/stolostron/library-go has been inactive for years, comfirmed with the repo owner, the repo is not been maintained in the furture.
Teh curator repo only use `LoadConfig` , but the only pattern is `LoadConfig("","","")`. So we can replace it with the `rest.InClusterConfig()` directly.
> Remove the dependency to stolostron lib-go.

- Dockerfile.prow
- Dockerfile.rhtap
The Go 1.22 builder image is built with UBI9, so passing the binary to a UBI8 image with CGO enabled is broken.
> Fix UBI version skew

- go.mod
- go.sum
https://issues.redhat.com/browse/ACM-16981
> ACM-16981: train-23 upgrade hive api to latest

- go.mod
- go.sum
Fix for CVE-2025-22868
- Bump x/oauth to 0.27.0
> Bump x/oauth to 0.27.0

- cmd/curator/curator.go
- pkg/jobs/hive/hive.go
- pkg/jobs/hive/hive_test.go
- pkg/jobs/utils/helpers.go
https://issues.redhat.com/browse/ACM-22079
Feature to use the image digest in ClusterVersion conditionalUpdates list when the non-recommended annotation is used.
- Added code to check the conditionalUpdates list for the image digest
- If not found will check the availableUpdates list
- If still not found will fall back to use the image tag for backward compatibility
- Also reverted a change from the server foundation team and brought back the `LoadConfig()` func so we can run the curator locally otherwise it can only run in a container which makes it hard for testing. The `LoadConfig()` func was originally from https://github.com/stolostron/library-go but the repo is no longer maintained.
> ACM-22079 Initial non-recommended image digest feature

- Dockerfile.rhtap
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
> chore(KONFLUX-6210): fix and set name and cpe label for cluster-curator-controller-mce-29
