OWNERS, deploy/controller/deployment.yaml
=> prefix the deployment with "cluster-"

pkg/controller/controller.go, pkg/controller/launcher/job.go, pkg/jobs/ansible/job.go, pkg/jobs/create/hive.go, pkg/jobs/curator.go, pkg/jobs/importer/managedcluster.go, pkg/jobs/rbac/rbac.go, pkg/jobs/secrets/secrets.go, pkg/jobs/utils/helpers.go
=> Update to generic copyright

Makefile.prow, pkg/controller/launcher/job.go, pkg/controller/launcher/job_test.go
Signed off by: Joshua Packer
* Bring test coverage for controller/launcher to 94%
=> Additional tests for controller/launcher

Makefile.prow, pkg/controller/launcher/job_test.go
Sign off by: Joshua Packer
* Fix Makefine.prow unit-tests param.
* Remove excessive logging
=> Unit test cleanup and init

Makefile.prow, pkg/controller/launcher/job_test.go
=> Release 2.3

Makefile.prow, README.md, pkg/jobs/ansible/job.go, pkg/jobs/secrets/secrets.go, pkg/jobs/secrets/secrets_test.go, pkg/jobs/utils/helpers.go
Signed off by: Joshua Packer
* Add unit-tests for secrets
* Remove README.md information about cluster templates (code to be removed THU)
* Fixed some bugs I found while writing tests
* Resolved a few more Sonarcloud issues
/cc @leena-jawale @hanqiuzh
=> Add secret unit tests. Adjust README.md

Makefile, Makefile.prow, cmd/curator/curator.go, go.mod, go.sum, pkg/jobs/create/hive.go
Signed off by: @jnpacker 
* Removed clusterDeployment support for AWS
* Added vendorizing to the build process
* Added Makefile.prow to the Makefile
/cc @itdove @hanqiuzh @leena-jawale
=> Remote clusterDeployment create options.

Makefile.prow, cmd/controller/controller_test.go, cmd/curator/curator.go, deploy/controller/deployment.yaml, pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go, pkg/jobs/rbac/rbac.go, pkg/jobs/rbac/rbac_test.go, pkg/jobs/utils/helpers.go
Signed off by: @jnpacker 
* Create a scale test (scale up and scale down) Completed 350 ManagedCluster test
* Create RBAC testing
* Fixed code smells
* Add pod resource specification
/cc @hanqiuzh @leena-jawale @itdove
=> Scale & Rbac tests. Pod resource definitions

Makefile.prow, pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go
* Fix broken ansible test
* Include Ansible test in `make unit-tests`
=> Fix ansible test failure and missing make cmd

Makefile.prow, pkg/jobs/utils/helpers.go, pkg/jobs/utils/helpers_test.go
* Create some tests for helper utils.
* Fix the PathSplitter function to better detect missing values
* Update Makefile.prow to call all tests vs individual calls.
* Test release-2.3 FF
=> Add tests for helper utils

pkg/jobs/ansible/job.go, pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go
* Add tests for Monitoring ClusterDeployment
* Fix some of the timeout code
=> Add a test for Monitoring Hive ClusterDeployments

sonar-project.properties
* Adding line return to fix sonar test exclude as per Leena & Jakob
=> Add a line to sonar-project.properties.

deploy/controller/deployment.yaml
Singed off by @jnpacker 
* Setup the new 2.3 image as the primary.
=> Add the correct upstream image

pkg/controller/launcher/job.go, pkg/jobs/importer/managedcluster.go, pkg/jobs/utils/helpers.go
Signed by @jnpacker 
* Fix sonarcloud Vulnerability, [link](https://sonarcloud.io/project/issues?branch=release-2.3&id=open-cluster-management_cluster-curator-controller&open=AXgmLC-cxJ0bDEbnsYu7&resolved=false&types=VULNERABILITY)
* Other sonar cloud fixes for repeating strings and code lines exceeding 120 characters.
/cc @Randy424 @hanqiuzh
=> Check error sonarissue

build/before-make.sh, build/git-hooks/commit-msg, build/git-hooks/pre-commit, cmd/curator/curator.go, go.mod, pkg/controller/launcher/job.go, pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go, pkg/jobs/hive/hive.go, pkg/jobs/utils/helpers.go
1. Shows job_finished false for the duration of the execution, message is the JOB name
=> Add a clustercurator-job condition

pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go
=> add label on manageclusterview

pkg/jobs/hive/hive.go
Curator status will show upgrade %
```
status:
conditions:
- lastTransitionTime: "2021-05-13T19:46:34Z"
message: curator-job-d2sdg
reason: Job_has_finished
status: "False"
type: clustercurator-job
- lastTransitionTime: "2021-05-13T19:46:44Z"
message: Completed executing init container
reason: Job_has_finished
status: "True"
type: upgrade-cluster
- lastTransitionTime: "2021-05-13T19:46:53Z"
message: 'Upgrade status - Working towards 4.6.16: 11% complete'
reason: Job_has_finished
status: "False"
type: monitor-upgrade
```
=> add % in the monitor-upgrade status

cmd/curator/curator.go, deploy/samples/sample-overridejob.yaml, pkg/jobs/ansible/job.go, pkg/jobs/utils/helpers.go
Signed-off-by: Joshua packer <jpacker@redhat.com>
* Has fix for `activate-and-monitor` condition remaining False after success
* Add support for NEW conditions with the AnsibleJob URL.
=> Ansiblejob status url

cmd/curator/curator.go
Signed-off-by: Joshua Packer <jpacker@redhat.com> 
This fixes the status never finishing for activate-and-monitor
=> Fix loss of jobChoice after activation, while monitoring

pkg/jobs/hive/hive.go
=> remove availableupdate check from channels

pkg/jobs/hive/hive.go
=> increase monitor upgrade timeout

Dockerfile.prow
* Change the build image
* Issue Ref: https://github.com/open-cluster-management/backlog/issues/11308
=> Change to new PROW multi-arch image builder

pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go
* Add platform key, but be weary that vmware has user credential
* Only filter the keys for VMware. Openstack is fine
=> Include install config

go.mod, go.sum
* Bugzilla 1961123 CVE-2021-29482
=> Bugzilla 1961123 CVE-2021-29482

cmd/curator/curator.go
=> update curatorjob status to add desiredcuration

cmd/curator/curator.go
=> add desiredcuration for successful job

pkg/controller/launcher/job.go
issue: https://github.com/open-cluster-management/backlog/issues/13946
=> don't run pre post hook for channel/upstream upgrade

go.mod, go.sum
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/open-cluster-management/backlog/issues/15987
=> upgrade hive to 1.1.16

Dockerfile.prow, go.mod
The related issue: https://github.com/open-cluster-management/backlog/issues/15570
=> upgrade go to version 1.17

Dockerfile.prow, go.mod
=> upgrade go version to 1.17

Makefile
issue: https://github.com/stolostron/backlog/issues/18987
=> remove unused variables from Makefile

go.mod, go.sum
The related issue: https://github.com/stolostron/backlog/issues/19219
=> fix missing dependency

Makefile
The related issue: https://github.com/stolostron/backlog/issues/19219
=> set tidy compatible version

Makefile, go.mod, go.sum
The related issue: https://github.com/stolostron/backlog/issues/19219
=> fix missing dependency in 2.4 branch

pkg/jobs/hive/hive.go
The related issue: https://github.com/stolostron/backlog/issues/19081
=> handle error in retry loop

go.mod, go.sum, pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go
=> add cluster info into extra-vars in upgrade job

pkg/controller/launcher/job_test.go, pkg/jobs/ansible/job.go, sonar-project.properties
Signed-off-by: xuezhaojun <zxue@redhat.com>
Relate issue: https://github.com/stolostron/backlog/issues/22701
Expecting coverage over 70%.
=> Improve coverage score

Dockerfile.prow, Makefile, build/run-unit-tests.sh, go.mod, pkg/jobs/hive/hive_test.go
https://github.com/stolostron/backlog/issues/22707
=> bump go to 1.18

deploy/crd/cluster.open-cluster-management.io_clustercurators.yaml, pkg/api/v1beta1/clustercurator_types.go, pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go
=> add inventory to curator spec

Makefile
Signed-off-by: xuezhaojun <zxue@redhat.com>
https://github.com/stolostron/backlog/issues/23452
=> Fix compat error

.gitignore, go.mod, go.sum, pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go, pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go, pkg/jobs/utils/helpers.go
story : https://github.com/stolostron/backlog/issues/23217
=> refactor with clc api

pkg/controller/launcher/job.go
it is already handled in import controller
Signed-off-by: Jian Qiu <jqiu@redhat.com>
=> Remove ns deletion job

go.mod, go.sum, pkg/jobs/hive/hive.go
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/25252
=> upgrade hive in 2.3

Dockerfile.prow, go.mod
=> upgrade to golang1.19

deploy/crd/cluster.open-cluster-management.io_clustercurators.yaml, pkg/api/v1beta1/clustercurator_types.go, pkg/jobs/ansible/job.go, pkg/jobs/ansible/job_test.go
Signed-off-by: Mike Ng <ming@redhat.com>
For https://issues.redhat.com/browse/ACM-1259
/assign @jnpacker 
/assign @xiangjingli 
/assign @elgnay 
FYI @KevinFCormier @Randy424
=> Add AnsibleJob job tags and skip tags support.

cmd/curator/curator.go, cmd/curator/curator_test.go, controllers/clustercurator_controller.go, go.mod, go.sum, pkg/jobs/utils/helpers.go, pkg/jobs/utils/helpers_test.go
Signed-off-by: Wei Liu <liuweixa@redhat.com>
=> save upgrade fields

pkg/jobs/hive/hive.go
Signed-off-by: Mike Ng <ming@redhat.com>
For https://github.com/stolostron/backlog/issues/26474
=> Increase the upgrade timeout from 120 to 480

CONTRIBUTING.md, DEBUGGING.md, README.md, deploy/controller/clusterrole.yaml, go.mod, go.sum, pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go, pkg/jobs/rbac/rbac.go, pkg/jobs/rbac/rbac_test.go
issue: https://issues.redhat.com/browse/ACM-2195
=> refactor installAttemptsLimit with pause annotation

OWNERS
=> add approvers/reviewers

pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go
The related issue: https://issues.redhat.com/browse/ACM-2531
=> update the clusterdeployment failure logic

pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go
The related issue: https://issues.redhat.com/browse/ACM-2531
=> remove cheking of ProvisionFailedCondition

cmd/curator/curator.go, cmd/curator/curator_test.go, deploy/crd/cluster.open-cluster-management.io_clustercurators.yaml, pkg/api/v1beta1/clustercurator_types.go, pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go, pkg/jobs/importer/managedcluster.go, pkg/jobs/importer/managedcluster_test.go, pkg/jobs/utils/helpers.go, pkg/jobs/utils/helpers_test.go
Signed-off-by: Wei Liu <liuweixa@redhat.com>
=> backport configurable timeout

cmd/curator/curator.go, cmd/curator/curator_test.go, controllers/clustercurator_controller.go, go.mod, go.sum, pkg/jobs/utils/helpers.go, pkg/jobs/utils/helpers_test.go
Signed-off-by: Wei Liu <liuweixa@redhat.com>
=> backport save upgrade fields (#140)

docs/README.md
=> Add more debug tips

pkg/jobs/hypershift/hypershift.go, pkg/jobs/hypershift/hypershift_test.go
https://issues.redhat.com/browse/ACM-8240
- Handle HostedClusters without auto-created-for-infra label
=> ACM-8240 Handle HostedClusters without auto-created-for-infra label

cmd/curator/curator.go, docs/README.md, pkg/jobs/utils/helpers.go
https://issues.redhat.com/browse/ACM-9145
- Fix clustercurator upgrade for imported clustersFeng import
=>  ACM-9145 Fix clustercurator upgrade for imported clusters MCE 2.4

deploy/crd/cluster.open-cluster-management.io_clustercurators.yaml, pkg/api/v1beta1/clustercurator_types.go
https://issues.redhat.com/browse/ACM-8980
- Update API description as requested by the doc team
=> ACM-8980 Update API description

deploy/crd/cluster.open-cluster-management.io_clustercurators.yaml, pkg/api/v1beta1/clustercurator_types.go
https://issues.redhat.com/browse/ACM-8980
- Update API description as requested by the doc team
=> ACM-8980 Fix API doc from suggestions made by the doc team

pkg/jobs/hive/hive.go, pkg/jobs/hive/hive_test.go
https://issues.redhat.com/browse/ACM-9334
- Backport non-recommended version upgrade
=> ACM-9334 Backport non-recommended version upgrade

pkg/jobs/hive/hive.go
https://issues.redhat.com/browse/ACM-11417
- Add retry when updating clusterversion during upgrade
=> ACM-11417 Add retry when updating clusterversion during upgrade

.tekton/cluster-curator-controller-mce-25-pull-request.yaml, .tekton/cluster-curator-controller-mce-25-push.yaml, Dockerfile.rhtap
https://issues.redhat.com/browse/ACM-10985
- Fix Konflux
=> ACM-10985 Fix Konflux

deploy/crd/cluster.open-cluster-management.io_clustercurators.yaml, pkg/api/v1beta1/clustercurator_types.go
https://issues.redhat.com/browse/ACM-8973
- Update API description
=> ACM-8973 Update API description

.tekton/cluster-curator-controller-mce-25-pull-request.yaml
https://issues.redhat.com/browse/ACM-10985
- Add missing params to Konflux
=> ACM-10985 Add missing params to Konflux

Dockerfile.rhtap
=> Use 1.21 builder

go.mod, go.sum
https://issues.redhat.com/browse/ACM-16314
=> ACM-16314: train-22 upgrade hive api to latest

.tekton/cluster-curator-controller-mce-28-pull-request.yaml, .tekton/cluster-curator-controller-mce-28-push.yaml
=> Add tekton to main

renovate.json
Disable Konflux Go dependency update
=> Disable Konflux Go dependency update

.tekton/cluster-curator-controller-mce-29-pull-request.yaml, .tekton/cluster-curator-controller-mce-29-push.yaml, Dockerfile.rhtap, Makefile
https://issues.redhat.com/browse/ACM-20489
=> fix go build failure in konflux pipeline

.tekton/cluster-curator-controller-mce-29-pull-request.yaml, .tekton/cluster-curator-controller-mce-29-push.yaml
* Update Konflux references
* Add missing param
---------
=> Update Konflux references (#407)
